export const SET_CONFIG_PATH = 'SET_CONFIG_PATH';
export const OPEN_PROJECT_SETTINGS = 'OPEN_PROJECT_SETTINGS';
export const CLOSE_PROJECT_SETTINGS = 'CLOSE_PROJECT_SETTINGS';
export const SET_LOCAL_PATH = 'SET_LOCAL_PATH';